// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessage = {
    role: 'user' | 'assistant';
    content: string;
};

export type role = 'user' | 'assistant';

export type ChatRequest = {
    message: string;
    profile?: (UserProfileInput | null);
    history?: Array<ChatMessage>;
};

export type ChatResponse = {
    reply: string;
    products_used: Array<(string)>;
    match_scores?: Array<MatchResultItem>;
    disclaimer: string;
};

export type FinancialProfileUpdate = {
    monthly_income?: (number | null);
    goal?: (string | null);
    has_credit_history?: (boolean | null);
    employment?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MatchRequest = {
    profile: UserProfileInput;
    product_types?: (Array<('credit_card' | 'debit_card' | 'loan' | 'savings' | 'insurance')> | null);
    limit?: number;
};

export type MatchResponse = {
    results: Array<MatchResultItem>;
    disclaimer: string;
};

export type MatchResultItem = {
    product_id: string;
    nombre_producto: string;
    banco: string;
    tipo_producto: string;
    score: number;
    reasons: Array<(string)>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProductData = {
    nombre_producto: string;
    banco: string;
    tipo_producto: 'credit_card' | 'debit_card' | 'loan' | 'savings' | 'insurance';
    anualidad?: (number | null);
    tasa_interes?: (number | null);
    requisitos?: Array<(string)>;
    beneficios?: Array<(string)>;
    promociones?: Array<Promocion>;
};

export type tipo_producto = 'credit_card' | 'debit_card' | 'loan' | 'savings' | 'insurance';

export type ProductPublic = {
    id: string;
    nombre_producto: string;
    banco: string;
    tipo_producto: 'credit_card' | 'debit_card' | 'loan' | 'savings' | 'insurance';
    source_url?: (string | null);
    normalized: {
        [key: string]: unknown;
    };
    last_updated?: (string | null);
    disclaimer: string;
};

export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
    disclaimer: string;
};

export type Promocion = {
    comercio?: (string | null);
    descuento_pct?: (number | null);
    tipo_tarjeta?: (string | null);
    vigencia?: (string | null);
    descripcion?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserProfileInput = {
    monthly_income?: (number | null);
    goal?: (string | null);
    has_credit_history?: (boolean | null);
    employment?: ('formal' | 'informal' | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Payload que envía n8n (scraping externo con Firecrawl) al webhook de ingesta.
 */
export type WebhookIngestRequest = {
    bank_slug: string;
    source_url: string;
    product: ProductData;
    raw?: ({
    [key: string]: unknown;
} | null);
};

export type AdminIngestRunDiscoverData = {
    bankSlug: string;
};

export type AdminIngestRunDiscoverResponse = ({
    [key: string]: unknown;
});

export type AdminIngestRunExtractData = {
    bankSlug: string;
    limit?: number;
};

export type AdminIngestRunExtractResponse = ({
    [key: string]: unknown;
});

export type AdminIngestRunWebhookIngestData = {
    requestBody: WebhookIngestRequest;
    xIngestApiKey?: (string | null);
};

export type AdminIngestRunWebhookIngestResponse = ({
    [key: string]: unknown;
});

export type AdvisorAdvisorMatchData = {
    requestBody: MatchRequest;
};

export type AdvisorAdvisorMatchResponse = (MatchResponse);

export type AdvisorAdvisorChatData = {
    requestBody: ChatRequest;
};

export type AdvisorAdvisorChatResponse = (ChatResponse);

export type FavoritesListMyFavoritesResponse = (ProductsPublic);

export type FavoritesAddFavoriteData = {
    productId: string;
};

export type FavoritesAddFavoriteResponse = (ProductPublic);

export type FavoritesRemoveFavoriteData = {
    productId: string;
};

export type FavoritesRemoveFavoriteResponse = (void);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProductsListProductsData = {
    banco?: (string | null);
    limit?: number;
    skip?: number;
    tipoProducto?: ('credit_card' | 'debit_card' | 'loan' | 'savings' | 'insurance' | null);
};

export type ProductsListProductsResponse = (ProductsPublic);

export type ProductsGetProductData = {
    productId: string;
};

export type ProductsGetProductResponse = (ProductPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdateFinancialProfileMeData = {
    requestBody: FinancialProfileUpdate;
};

export type UsersUpdateFinancialProfileMeResponse = (Message);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = ({
    [key: string]: (boolean | string);
});

export type UtilsGetDisclaimerResponse = (Message);